<?php

namespace Database\Seeders\Core;

use App\Enums\SubjectCategory;
use App\Models\Subject;
use Illuminate\Database\Seeder;

class SubjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $subjects = [
            // LINGUAGENS E SUAS TECNOLOGIAS
            [
                'code' => 'LP',
                'normalized_code' => 'lp',
                'name' => 'Língua Portuguesa',
                'category' => SubjectCategory::LINGUAGENS,
                'status' => 'active',
                'bncc_code' => 'LP',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['leitura', 'escrita', 'literatura', 'gramática']),
            ],
            [
                'code' => 'ING',
                'normalized_code' => 'ing',
                'name' => 'Inglês',
                'category' => SubjectCategory::LINGUAGENS,
                'status' => 'active',
                'bncc_code' => 'ING',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['idioma', 'comunicação', 'gramática']),
            ],
            [
                'code' => 'ESP',
                'normalized_code' => 'esp',
                'name' => 'Espanhol',
                'category' => SubjectCategory::LINGUAGENS,
                'status' => 'active',
                'bncc_code' => 'ESP',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['idioma', 'comunicação', 'cultural']),
            ],
            [
                'code' => 'ARTES',
                'normalized_code' => 'arte',
                'name' => 'Artes',
                'category' => SubjectCategory::LINGUAGENS,
                'status' => 'active',
                'bncc_code' => 'ARTES',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['criatividade', 'expressão', 'cultura']),
            ],
            [
                'code' => 'ED-FIS',
                'normalized_code' => 'edfis',
                'name' => 'Educação Física',
                'category' => SubjectCategory::LINGUAGENS,
                'status' => 'active',
                'bncc_code' => 'ED-FIS',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['esporte', 'saúde', 'movimento']),
            ],

            // MATEMÁTICA E SUAS TECNOLOGIAS
            [
                'code' => 'MAT',
                'normalized_code' => 'mat',
                'name' => 'Matemática',
                'category' => SubjectCategory::MATEMATICA,
                'status' => 'active',
                'bncc_code' => 'MAT',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['números', 'álgebra', 'geometria', 'cálculo']),
            ],
            [
                'code' => 'ALG',
                'normalized_code' => 'alg',
                'name' => 'Álgebra',
                'category' => SubjectCategory::MATEMATICA,
                'status' => 'active',
                'bncc_code' => 'ALG',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['matemática', 'equações', 'funções']),
            ],
            [
                'code' => 'GEO-MAT',
                'normalized_code' => 'geomat',
                'name' => 'Geometria',
                'category' => SubjectCategory::MATEMATICA,
                'status' => 'active',
                'bncc_code' => 'GEO-MAT',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['espaço', 'formas', 'medidas']),
            ],
            [
                'code' => 'TRIG',
                'normalized_code' => 'trig',
                'name' => 'Trigonometria',
                'category' => SubjectCategory::MATEMATICA,
                'status' => 'active',
                'bncc_code' => 'TRIG',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['matemática', 'ângulos', 'funções']),
            ],
            [
                'code' => 'STAT',
                'normalized_code' => 'stat',
                'name' => 'Estatística e Probabilidade',
                'category' => SubjectCategory::MATEMATICA,
                'status' => 'active',
                'bncc_code' => 'STAT',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['dados', 'análise', 'probabilidade']),
            ],

            // CIÊNCIAS DA NATUREZA E SUAS TECNOLOGIAS
            [
                'code' => 'BIO',
                'normalized_code' => 'bio',
                'name' => 'Biologia',
                'category' => SubjectCategory::CIENCIAS_EXATAS,
                'status' => 'active',
                'bncc_code' => 'BIO',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['vida', 'organismos', 'evolução']),
            ],
            [
                'code' => 'FIS',
                'normalized_code' => 'fis',
                'name' => 'Física',
                'category' => SubjectCategory::CIENCIAS_EXATAS,
                'status' => 'active',
                'bncc_code' => 'FIS',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['movimento', 'energia', 'força']),
            ],
            [
                'code' => 'QUIM',
                'normalized_code' => 'qui',
                'name' => 'Química',
                'category' => SubjectCategory::CIENCIAS_EXATAS,
                'status' => 'active',
                'bncc_code' => 'QUIM',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['elementos', 'reações', 'matéria']),
            ],
            [
                'code' => 'CIE',
                'normalized_code' => 'cie',
                'name' => 'Ciências Naturais',
                'category' => SubjectCategory::CIENCIAS_EXATAS,
                'status' => 'active',
                'bncc_code' => 'CIE',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['natureza', 'ambiente', 'sustentabilidade']),
            ],

            // CIÊNCIAS HUMANAS E SOCIAIS APLICADAS
            [
                'code' => 'HIS',
                'normalized_code' => 'his',
                'name' => 'História',
                'category' => SubjectCategory::CIENCIAS_HUMANAS,
                'status' => 'active',
                'bncc_code' => 'HIS',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['passado', 'sociedade', 'cultura']),
            ],
            [
                'code' => 'GEO',
                'normalized_code' => 'geo',
                'name' => 'Geografia',
                'category' => SubjectCategory::CIENCIAS_HUMANAS,
                'status' => 'active',
                'bncc_code' => 'GEO',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['espaço', 'população', 'ambiente']),
            ],
            [
                'code' => 'SOCIO',
                'normalized_code' => 'socio',
                'name' => 'Sociologia',
                'category' => SubjectCategory::CIENCIAS_HUMANAS,
                'status' => 'active',
                'bncc_code' => 'SOCIO',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['sociedade', 'cultura', 'relações']),
            ],
            [
                'code' => 'FILO',
                'normalized_code' => 'filo',
                'name' => 'Filosofia',
                'category' => SubjectCategory::CIENCIAS_HUMANAS,
                'status' => 'active',
                'bncc_code' => 'FILO',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['pensamento', 'ética', 'conhecimento']),
            ],
            [
                'code' => 'ECON',
                'normalized_code' => 'econ',
                'name' => 'Economia',
                'category' => SubjectCategory::CIENCIAS_HUMANAS,
                'status' => 'active',
                'bncc_code' => 'ECON',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['mercado', 'produção', 'consumo']),
            ],
            [
                'code' => 'DIR',
                'normalized_code' => 'dir',
                'name' => 'Direito e Cidadania',
                'category' => SubjectCategory::CIENCIAS_HUMANAS,
                'status' => 'active',
                'bncc_code' => 'DIR',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['leis', 'direitos', 'cidadania']),
            ],
            [
                'code' => 'ANT',
                'normalized_code' => 'ant',
                'name' => 'Antropologia',
                'category' => SubjectCategory::CIENCIAS_HUMANAS,
                'status' => 'active',
                'bncc_code' => 'ANT',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['cultura', 'sociedade', 'tradição']),
            ],

            // FORMAÇÃO GERAL E TÉCNICA
            [
                'code' => 'IT',
                'normalized_code' => 'it',
                'name' => 'Informática e Tecnologia',
                'category' => SubjectCategory::LINGUAGENS,
                'status' => 'active',
                'bncc_code' => 'IT',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['computador', 'programação', 'digital']),
            ],
            [
                'code' => 'PROM',
                'normalized_code' => 'prom',
                'name' => 'Projeto de Vida',
                'category' => SubjectCategory::CIENCIAS_HUMANAS,
                'status' => 'active',
                'bncc_code' => 'PROM',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['desenvolvimento', 'carreira', 'bem-estar']),
            ],
            [
                'code' => 'EME',
                'normalized_code' => 'eme',
                'name' => 'Educação em Saúde',
                'category' => SubjectCategory::CIENCIAS_EXATAS,
                'status' => 'active',
                'bncc_code' => 'EME',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['saúde', 'higiene', 'prevenção']),
            ],
            [
                'code' => 'ESTUDO',
                'normalized_code' => 'est',
                'name' => 'Estudo Dirigido',
                'category' => SubjectCategory::LINGUAGENS,
                'status' => 'active',
                'bncc_code' => 'EST',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['aprendizagem', 'reforço', 'apoio']),
            ],
            [
                'code' => 'REDACAO',
                'normalized_code' => 'red',
                'name' => 'Redação',
                'category' => SubjectCategory::LINGUAGENS,
                'status' => 'active',
                'bncc_code' => 'RED',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['escrita', 'composição', 'texto']),
            ],
            [
                'code' => 'REFORÇO-MAT',
                'normalized_code' => 'refmat',
                'name' => 'Reforço de Matemática',
                'category' => SubjectCategory::MATEMATICA,
                'status' => 'active',
                'bncc_code' => 'REFMAT',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['reforço', 'apoio', 'matemática']),
            ],
            [
                'code' => 'REFORÇO-PORT',
                'normalized_code' => 'refport',
                'name' => 'Reforço de Português',
                'category' => SubjectCategory::LINGUAGENS,
                'status' => 'active',
                'bncc_code' => 'REFPORT',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['reforço', 'apoio', 'português']),
            ],
            [
                'code' => 'LIBRAS',
                'normalized_code' => 'libras',
                'name' => 'Libras',
                'category' => SubjectCategory::LINGUAGENS,
                'status' => 'active',
                'bncc_code' => 'LIBRAS',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['idioma', 'inclusão', 'sinais']),
            ],
            [
                'code' => 'PRAT-PROF',
                'normalized_code' => 'pratprof',
                'name' => 'Prática Profissional',
                'category' => SubjectCategory::CIENCIAS_HUMANAS,
                'status' => 'active',
                'bncc_code' => 'PRATPROF',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['trabalho', 'prática', 'profissão']),
            ],
            [
                'code' => 'ENEM-PREP',
                'normalized_code' => 'enemprep',
                'name' => 'Preparação ENEM',
                'category' => SubjectCategory::MATEMATICA,
                'status' => 'active',
                'bncc_code' => 'ENEMPREP',
                'bncc_reference_url' => 'https://bncc.mec.gov.br/',
                'tags' => json_encode(['vestibular', 'preparação', 'enem']),
            ],
        ];

        foreach ($subjects as $subject) {
            Subject::updateOrCreate(
                [
                    'code' => $subject['code'],
                    'category' => $subject['category']->value,
                ],
                $subject
            );
        }
    }
}
