<?php

return [
    'students.view'              => ['academic.students.view_any', 'academic.students.view'],
    'students.create'            => 'academic.students.create',
    'students.edit'              => 'academic.students.update',
    'students.delete'            => 'academic.students.delete',
    'students.export'            => 'academic.students.view_any',
    'enrollments.view'           => ['academic.enrollments.view_any', 'academic.enrollments.view'],
    'enrollments.create'         => 'academic.enrollments.create',
    'enrollments.edit'           => 'academic.enrollments.update',
    'enrollments.delete'         => 'academic.enrollments.cancel',
    'enrollments.export'         => 'academic.enrollments.view_any',
    'classes.view'               => ['academic.classes.view_any', 'academic.classes.view'],
    'classes.create'             => 'academic.classes.create',
    'classes.edit'               => 'academic.classes.update',
    'classes.delete'             => 'academic.classes.delete',
    'classes.export'             => 'academic.classes.view_any',
    'subjects.view'              => ['academic.subjects.view_any', 'academic.subjects.view'],
    'subjects.create'            => 'academic.subjects.create',
    'subjects.edit'              => 'academic.subjects.update',
    'subjects.delete'            => 'academic.subjects.delete',
    'subjects.export'            => 'academic.subjects.view_any',
    'grade_levels.view'          => ['academic.grade_levels.view_any', 'academic.grade_levels.view'],
    'grade_levels.create'        => 'academic.grade_levels.create',
    'grade_levels.edit'          => 'academic.grade_levels.update',
    'grade_levels.delete'        => 'academic.grade_levels.delete',
    'grade_levels.export'        => 'academic.grade_levels.view_any',
    'school_years.view'          => ['academic.school_years.view_any', 'academic.school_years.view'],
    'school_years.create'        => 'academic.school_years.create',
    'school_years.edit'          => 'academic.school_years.update',
    'school_years.delete'        => 'academic.school_years.delete',
    'school_years.export'        => 'academic.school_years.view_any',
    'grades.view'                => ['academic.grades.view_any', 'academic.grades.view'],
    'grades.create'              => 'academic.grades.create',
    'grades.edit'                => 'academic.grades.update',
    'grades.delete'              => 'academic.grades.delete',
    'grades.export'              => 'academic.grades.view_any',
    'teachers.view'              => ['admin.teachers.view_any', 'admin.teachers.view'],
    'teachers.create'            => 'admin.teachers.create',
    'teachers.edit'              => 'admin.teachers.update',
    'teachers.delete'            => 'admin.teachers.delete',
    'teachers.export'            => 'admin.teachers.view_any',
    'teacher_assignments.view'   => [
        'admin.teachers.assignments.view_any',
        'admin.teachers.assignments.view',
    ],
    'teacher_assignments.create' => 'admin.teachers.assignments.create',
    'teacher_assignments.edit'   => 'admin.teachers.assignments.update',
    'teacher_assignments.delete' => 'admin.teachers.assignments.delete',
    'teacher_assignments.export' => 'admin.teachers.assignments.view_any',
    'admin.teachers.assignments.manage' => [
        'admin.teachers.assignments.view_any',
        'admin.teachers.assignments.view',
        'admin.teachers.assignments.create',
        'admin.teachers.assignments.update',
        'admin.teachers.assignments.delete',
    ],
    'users.view'                 => ['system.users.view_any', 'system.users.view'],
    'users.create'               => 'system.users.create',
    'users.edit'                 => 'system.users.update',
    'users.delete'               => 'system.users.delete',
    'users.export'               => 'system.users.view_any',
    'roles.view'                 => ['system.roles.view_any', 'system.roles.view'],
    'roles.create'               => 'system.roles.create',
    'roles.edit'                 => 'system.roles.update',
    'roles.delete'               => 'system.roles.delete',
    'roles.export'               => 'system.roles.view_any',
    'grades.view.own'            => 'teacher.grades.view',
    'grades.create.own'          => 'teacher.grades.create',
    'grades.update.own'          => 'teacher.grades.update',
    'attendance.mark.own'        => 'teacher.attendance.create',
    'classes.view.own'           => 'teacher.classes.view',
    'subjects.view.own'          => 'teacher.subjects.view',
    'grades.view.self'           => 'student.grades.view',
    'subjects.view.self'         => 'student.subjects.view',
];
