<?php

return [
    [
        'name' => 'student.dashboard.view',
        'label' => 'Acessar painel do aluno',
        'module' => 'Portal do Aluno',
        'type' => 'view',
    ],
    [
        'name' => 'student.grades.view',
        'label' => 'Ver minhas notas',
        'module' => 'Portal do Aluno',
        'type' => 'view',
    ],
    [
        'name' => 'student.attendance.view',
        'label' => 'Ver minhas faltas',
        'module' => 'Portal do Aluno',
        'type' => 'view',
    ],
    [
        'name' => 'student.subjects.view',
        'label' => 'Ver minhas disciplinas',
        'module' => 'Portal do Aluno',
        'type' => 'view',
    ],
    [
        'name' => 'student.calendar.view',
        'label' => 'Ver calendário acadêmico',
        'module' => 'Portal do Aluno',
        'type' => 'view',
    ],
    [
        'name' => 'student.assessments.view',
        'label' => 'Ver minhas avaliações',
        'module' => 'Portal do Aluno',
        'type' => 'view',
    ],
    [
        'name' => 'student.profile.view',
        'label' => 'Ver meu perfil',
        'module' => 'Portal do Aluno',
        'type' => 'view',
    ],
    [
        'name' => 'student.documents.view',
        'label' => 'Ver documentos acadêmicos',
        'module' => 'Portal do Aluno',
        'type' => 'view',
    ],
    [
        'name' => 'student.report-card.download',
        'label' => 'Baixar boletim',
        'module' => 'Portal do Aluno',
        'type' => 'download',
    ],

    [
        'name' => 'teacher.dashboard.view',
        'label' => 'Acessar painel do professor',
        'module' => 'Portal do Professor',
        'type' => 'view',
    ],
    [
        'name' => 'teacher.classes.view',
        'label' => 'Ver minhas turmas',
        'module' => 'Portal do Professor',
        'type' => 'view',
    ],
    [
        'name' => 'teacher.subjects.view',
        'label' => 'Ver minhas disciplinas',
        'module' => 'Portal do Professor',
        'type' => 'view',
    ],
    [
        'name' => 'teacher.schedule.view',
        'label' => 'Ver agenda de aulas',
        'module' => 'Portal do Professor',
        'type' => 'view',
    ],
    [
        'name' => 'teacher.attendance.view',
        'label' => 'Ver frequência',
        'module' => 'Portal do Professor',
        'type' => 'view',
    ],
    [
        'name' => 'teacher.attendance.create',
        'label' => 'Lançar frequência',
        'module' => 'Portal do Professor',
        'type' => 'create',
    ],
    [
        'name' => 'teacher.attendance.update',
        'label' => 'Corrigir frequência',
        'module' => 'Portal do Professor',
        'type' => 'update',
    ],
    [
        'name' => 'teacher.assessments.view',
        'label' => 'Ver avaliações',
        'module' => 'Portal do Professor',
        'type' => 'view',
    ],
    [
        'name' => 'teacher.assessments.create',
        'label' => 'Criar avaliações',
        'module' => 'Portal do Professor',
        'type' => 'create',
    ],
    [
        'name' => 'teacher.assessments.update',
        'label' => 'Editar avaliações',
        'module' => 'Portal do Professor',
        'type' => 'update',
    ],
    [
        'name' => 'teacher.assessments.close',
        'label' => 'Fechar avaliações',
        'module' => 'Portal do Professor',
        'type' => 'close',
    ],
    [
        'name' => 'teacher.grades.view',
        'label' => 'Ver notas lançadas',
        'module' => 'Portal do Professor',
        'type' => 'view',
    ],
    [
        'name' => 'teacher.grades.create',
        'label' => 'Lançar notas',
        'module' => 'Portal do Professor',
        'type' => 'create',
    ],
    [
        'name' => 'teacher.grades.update',
        'label' => 'Corrigir notas',
        'module' => 'Portal do Professor',
        'type' => 'update',
    ],
    [
        'name' => 'teacher.grades.publish',
        'label' => 'Publicar notas',
        'module' => 'Portal do Professor',
        'type' => 'publish',
    ],
    [
        'name' => 'teacher.announcements.view',
        'label' => 'Ver comunicados',
        'module' => 'Portal do Professor',
        'type' => 'view',
    ],
    [
        'name' => 'teacher.pending.view',
        'label' => 'Ver pendências',
        'module' => 'Portal do Professor',
        'type' => 'view',
    ],
    [
        'name' => 'teacher.profile.view',
        'label' => 'Ver meu perfil',
        'module' => 'Portal do Professor',
        'type' => 'view',
    ],
    [
        'name' => 'teacher.profile.update-basic',
        'label' => 'Atualizar dados básicos do meu perfil',
        'module' => 'Portal do Professor',
        'type' => 'update',
    ],

    [
        'name' => 'academic.students.view_any',
        'label' => 'Listar alunos',
        'module' => 'Secretaria Acadêmica',
        'type' => 'view_any',
    ],
    [
        'name' => 'academic.students.view',
        'label' => 'Visualizar aluno',
        'module' => 'Secretaria Acadêmica',
        'type' => 'view',
    ],
    [
        'name' => 'academic.students.create',
        'label' => 'Cadastrar aluno',
        'module' => 'Secretaria Acadêmica',
        'type' => 'create',
    ],
    [
        'name' => 'academic.students.update',
        'label' => 'Editar aluno',
        'module' => 'Secretaria Acadêmica',
        'type' => 'update',
    ],
    [
        'name' => 'academic.students.delete',
        'label' => 'Inativar aluno',
        'module' => 'Secretaria Acadêmica',
        'type' => 'delete',
    ],
    [
        'name' => 'academic.enrollments.view_any',
        'label' => 'Listar matrículas',
        'module' => 'Secretaria Acadêmica',
        'type' => 'view_any',
    ],
    [
        'name' => 'academic.enrollments.create',
        'label' => 'Realizar matrícula',
        'module' => 'Secretaria Acadêmica',
        'type' => 'create',
    ],
    [
        'name' => 'academic.enrollments.update',
        'label' => 'Alterar matrícula',
        'module' => 'Secretaria Acadêmica',
        'type' => 'update',
    ],
    [
        'name' => 'academic.enrollments.cancel',
        'label' => 'Cancelar matrícula',
        'module' => 'Secretaria Acadêmica',
        'type' => 'cancel',
    ],
    [
        'name' => 'academic.classes.view_any',
        'label' => 'Listar turmas',
        'module' => 'Secretaria Acadêmica',
        'type' => 'view_any',
    ],
    [
        'name' => 'academic.classes.create',
        'label' => 'Criar turmas',
        'module' => 'Secretaria Acadêmica',
        'type' => 'create',
    ],
    [
        'name' => 'academic.classes.update',
        'label' => 'Editar turmas',
        'module' => 'Secretaria Acadêmica',
        'type' => 'update',
    ],
    [
        'name' => 'academic.subjects.view_any',
        'label' => 'Listar disciplinas',
        'module' => 'Secretaria Acadêmica',
        'type' => 'view_any',
    ],
    [
        'name' => 'academic.subjects.create',
        'label' => 'Criar disciplinas',
        'module' => 'Secretaria Acadêmica',
        'type' => 'create',
    ],
    [
        'name' => 'academic.subjects.update',
        'label' => 'Editar disciplinas',
        'module' => 'Secretaria Acadêmica',
        'type' => 'update',
    ],
    [
        'name' => 'academic.calendar.manage',
        'label' => 'Gerenciar calendário acadêmico',
        'module' => 'Secretaria Acadêmica',
        'type' => 'manage',
    ],

    [
        'name' => 'admin.teachers.view_any',
        'label' => 'Listar professores',
        'module' => 'Professores - Administrativo',
        'type' => 'view_any',
    ],
    [
        'name' => 'admin.teachers.view',
        'label' => 'Visualizar professor',
        'module' => 'Professores - Administrativo',
        'type' => 'view',
    ],
    [
        'name' => 'admin.teachers.create',
        'label' => 'Cadastrar professor',
        'module' => 'Professores - Administrativo',
        'type' => 'create',
    ],
    [
        'name' => 'admin.teachers.update',
        'label' => 'Editar professor',
        'module' => 'Professores - Administrativo',
        'type' => 'update',
    ],
    [
        'name' => 'admin.teachers.delete',
        'label' => 'Inativar professor',
        'module' => 'Professores - Administrativo',
        'type' => 'delete',
    ],
    [
        'name' => 'admin.teachers.documents.manage',
        'label' => 'Gerenciar documentos do professor',
        'module' => 'Professores - Administrativo',
        'type' => 'manage',
    ],
    [
        'name' => 'admin.teachers.contracts.manage',
        'label' => 'Gerenciar contratos do professor',
        'module' => 'Professores - Administrativo',
        'type' => 'manage',
    ],
    [
        'name' => 'admin.teachers.assignments.manage',
        'label' => 'Gerenciar alocações do professor',
        'module' => 'Professores - Administrativo',
        'type' => 'manage',
    ],
    [
        'name' => 'admin.teachers.leaves.manage',
        'label' => 'Gerenciar afastamentos do professor',
        'module' => 'Professores - Administrativo',
        'type' => 'manage',
    ],

    [
        'name' => 'financial.dashboard.view',
        'label' => 'Acessar painel financeiro',
        'module' => 'Financeiro',
        'type' => 'view',
    ],
    [
        'name' => 'financial.charges.view_any',
        'label' => 'Listar cobranças',
        'module' => 'Financeiro',
        'type' => 'view_any',
    ],
    [
        'name' => 'financial.charges.create',
        'label' => 'Criar cobrança',
        'module' => 'Financeiro',
        'type' => 'create',
    ],
    [
        'name' => 'financial.charges.update',
        'label' => 'Editar cobrança',
        'module' => 'Financeiro',
        'type' => 'update',
    ],
    [
        'name' => 'financial.payments.view_any',
        'label' => 'Listar pagamentos',
        'module' => 'Financeiro',
        'type' => 'view_any',
    ],
    [
        'name' => 'financial.payments.confirm',
        'label' => 'Confirmar pagamento',
        'module' => 'Financeiro',
        'type' => 'confirm',
    ],
    [
        'name' => 'financial.reports.view',
        'label' => 'Ver relatórios financeiros',
        'module' => 'Financeiro',
        'type' => 'view',
    ],
    [
        'name' => 'financial.reports.export',
        'label' => 'Exportar relatórios financeiros',
        'module' => 'Financeiro',
        'type' => 'export',
    ],

    [
        'name' => 'reports.academic.view',
        'label' => 'Ver relatórios acadêmicos',
        'module' => 'Relatórios',
        'type' => 'view',
    ],
    [
        'name' => 'reports.academic.export',
        'label' => 'Exportar relatórios acadêmicos',
        'module' => 'Relatórios',
        'type' => 'export',
    ],
    [
        'name' => 'reports.attendance.view',
        'label' => 'Ver relatórios de frequência',
        'module' => 'Relatórios',
        'type' => 'view',
    ],
    [
        'name' => 'reports.attendance.export',
        'label' => 'Exportar relatórios de frequência',
        'module' => 'Relatórios',
        'type' => 'export',
    ],
    [
        'name' => 'reports.grades.view',
        'label' => 'Ver relatórios de notas',
        'module' => 'Relatórios',
        'type' => 'view',
    ],
    [
        'name' => 'reports.grades.export',
        'label' => 'Exportar relatórios de notas',
        'module' => 'Relatórios',
        'type' => 'export',
    ],
    [
        'name' => 'reports.students.view',
        'label' => 'Ver relatórios de alunos',
        'module' => 'Relatórios',
        'type' => 'view',
    ],
    [
        'name' => 'reports.teachers.view',
        'label' => 'Ver relatórios de professores',
        'module' => 'Relatórios',
        'type' => 'view',
    ],

    [
        'name' => 'system.users.view_any',
        'label' => 'Listar usuários',
        'module' => 'Sistema',
        'type' => 'view_any',
    ],
    [
        'name' => 'system.users.create',
        'label' => 'Criar usuários',
        'module' => 'Sistema',
        'type' => 'create',
    ],
    [
        'name' => 'system.users.update',
        'label' => 'Editar usuários',
        'module' => 'Sistema',
        'type' => 'update',
    ],
    [
        'name' => 'system.users.block',
        'label' => 'Bloquear usuários',
        'module' => 'Sistema',
        'type' => 'block',
    ],
    [
        'name' => 'system.roles.view_any',
        'label' => 'Listar perfis',
        'module' => 'Sistema',
        'type' => 'view_any',
    ],
    [
        'name' => 'system.roles.create',
        'label' => 'Criar perfis',
        'module' => 'Sistema',
        'type' => 'create',
    ],
    [
        'name' => 'system.roles.update',
        'label' => 'Editar perfis',
        'module' => 'Sistema',
        'type' => 'update',
    ],
    [
        'name' => 'system.permissions.manage',
        'label' => 'Gerenciar permissões',
        'module' => 'Sistema',
        'type' => 'manage',
    ],
    [
        'name' => 'system.audit.view',
        'label' => 'Ver auditoria',
        'module' => 'Sistema',
        'type' => 'view',
    ],
    [
        'name' => 'system.settings.manage',
        'label' => 'Gerenciar configurações do sistema',
        'module' => 'Sistema',
        'type' => 'manage',
    ],

    [
        'name' => 'guardian.dashboard.view',
        'label' => 'Acessar painel do responsável',
        'module' => 'Responsável',
        'type' => 'view',
    ],
    [
        'name' => 'guardian.students.view',
        'label' => 'Ver alunos vinculados',
        'module' => 'Responsável',
        'type' => 'view',
    ],
    [
        'name' => 'guardian.grades.view',
        'label' => 'Ver notas do aluno vinculado',
        'module' => 'Responsável',
        'type' => 'view',
    ],
    [
        'name' => 'guardian.attendance.view',
        'label' => 'Ver frequência do aluno vinculado',
        'module' => 'Responsável',
        'type' => 'view',
    ],
    [
        'name' => 'guardian.financial.view',
        'label' => 'Ver financeiro do aluno vinculado',
        'module' => 'Responsável',
        'type' => 'view',
    ],
    [
        'name' => 'guardian.announcements.view',
        'label' => 'Ver comunicados',
        'module' => 'Responsável',
        'type' => 'view',
    ],
];
